---
title: "Instacart Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

Column {data-width=350}
-----------------------------------------------------------------------



```{r}
set.seed(1)

data("instacart")

 
instacart = 
  instacart %>% 
  mutate(
    reordered = recode(reordered, "1" = "Reordered", "0" = "Not Reordered"),
    reordered = factor(reordered, levels = c("Not Reordered", "Reordered")),
    order_dow = recode(order_dow, "0" = "Sunday", "1" = "Monday", 
                       "2" = "Tuesday", "3" = "Wednesday", 
                       "4" = "Thursday", "5" = "Friday", 
                       "6" = "Saturday"), 
    order_dow = factor(order_dow, levels = c("Monday", "Tuesday", 
                                             "Wednesday", "Thursday", 
                                             "Friday", "Saturday",
                                             "Sunday"))) %>% 
  select(aisle, department, order_hour_of_day, order_dow, product_name,
         reordered, user_id) %>% 
  sample_n(500)
```


### Location of the Aisles for Reordered Items


```{r}
instacart %>% 
  mutate(text_label = str_c(product_name)) %>%
  plot_ly(
    x = ~aisle, y = ~department, type = "scatter", mode = "markers",
    color = ~reordered, text = ~text_label, alpha = 0.5) %>% 
  layout(xaxis = list(title = "Aisle", tickangle = -45),
         yaxis = list(title = "Department"),
         margin = list(b = 100))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Number of Orders per Day

```{r}
instacart %>% 
  count(order_dow) %>% 
  mutate(fct_reorder(order_dow, n)) %>% 
  plot_ly(x = ~order_dow, y = ~n, color = ~order_dow, type = "bar") %>% 
  layout(xaxis = list(title = "Day", tickangle = -45),
         yaxis = list(title = "Number of Orders"),
         margin = list(b = 100),
         barmode = 'group')
```

### Hour of Day selected Aisles are most Visited

```{r}
common_aisle = 
  instacart %>% 
  filter(aisle == c("fresh vegetables", "fresh fruits", "packaged vegetables fruits",
         "yogurt", "packaged cheese", "water seltzer sparkling water")) %>%
  count(aisle, sort = TRUE)
```

```{r}
inner_join(instacart, common_aisle, by = "aisle") %>% 
  mutate(aisle = fct_reorder(aisle, order_hour_of_day)) %>%
  plot_ly(y = ~order_hour_of_day, color = ~aisle, type = "box",
          colors = "Set2") %>% 
  layout(yaxis = list(title = "Hour of Day"))
```



