---
title: "Association between Gender and Salary Setting at the Houston College of Medicine"
author: "Clement Mugenzi"
date: "12/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

Income inequality between men and women has been a point of debate over the years. To find our own answers, our team sought to examine the association between salary and gender at the Houston college of medicine. This was a cross-sectional study based on the salaries among faculties with varying expertise in the field of medicine. We created two regression models of baseline salary in 1994 and the increment of salary between 1994 and 1995, according to gender, department, years of experience, work emphasis, certification status, and rank. We found that gender was significantly associated with salary setting at baseline but that it was not a determining factor for the salary increase from between 1994 and 1995.

Title VII of the Civil Rights Act of 1964 is a federal law that prohibits employers from discriminating against employees on the basis of sex, race, color, national origin and religion[3]. Also, the equal pay act of 1963 requires that men and women in the same workplace be given equal pay for equal work. However, the U.S education system is one area that is not immune to this income gap problem. Several factors determine one’s compensation in the education system. Despite these legitimate factors that determine compensation, there are many cases that have been published claiming that female professors are getting paid less compared to their male colleagues while bearing the same, if not superior, titles or accolades.
The aim of this study is to examine the association between gender discrimination in setting salary within the Houston college of medicine where a female professor claimed, through a district court lawsuit, that there was evidence of discrimination against women in giving promotions and setting salaries. To support this, we built multiple regressionmodels using six predictor variables such as the subject's department, their area of expertise, whether or not they are board-certified, years of experience, and their position title. We tested for interactions and confounders that might be present between all the stated predictors and our main predictor of interest: the subject’s gender. Our response variables were the baseline salary in 1994 and the change in salary between 1994 and 1995.


























































